// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NIHR.ProfileManagement.Infrastructure.Repository;

#nullable disable

namespace NIHR.ProfileManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileManagementDbContext))]
    [Migration("20240718135845_01-Initial")]
    partial class _01Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.PersonNameDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("family");

                    b.Property<string>("Given")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("given");

                    b.Property<int>("ProfileInfoId")
                        .HasColumnType("int")
                        .HasColumnName("profileInfoId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileInfoId");

                    b.ToTable("profileInfoPersonName", (string)null);
                });

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("ProfileInfoId")
                        .HasColumnType("int")
                        .HasColumnName("profileInfoId");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("sub");

                    b.HasKey("Id");

                    b.HasIndex("ProfileInfoId");

                    b.ToTable("profileIdentity", (string)null);
                });

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileInfoDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.HasKey("Id");

                    b.ToTable("profileInfo", (string)null);
                });

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.PersonNameDbEntity", b =>
                {
                    b.HasOne("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileInfoDbEntity", "ProfileInfo")
                        .WithMany("Names")
                        .HasForeignKey("ProfileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profileInfoPersonName_profile");

                    b.Navigation("ProfileInfo");
                });

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileIdentity", b =>
                {
                    b.HasOne("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileInfoDbEntity", "ProfileInfo")
                        .WithMany("Identities")
                        .HasForeignKey("ProfileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profileIdentity_profile");

                    b.Navigation("ProfileInfo");
                });

            modelBuilder.Entity("NIHR.ProfileManagement.Infrastructure.Repository.Models.ProfileInfoDbEntity", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Names");
                });
#pragma warning restore 612, 618
        }
    }
}
